#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 25 16:33:56 2021

@author: aolza
"""
from configurations.default import *
import os
PREVIOUSHOSP=None
RESOURCEUSAGE=False
PREDICTORREGEX=r'PATIENT_ID|FEMALE|AGE_[0-9]+$|ACG|EDC_|HOSDOM|FRAILTY|RXMG|ingresoUrg'
# PREDICTORREGEX=r'PATIENT_ID|FEMALE|AGE_[0-9]+$|ACG|EDC_|HOSDOM|FRAILTY|RXMG_|INGRED_14GT|INDICE_PRIVACION'
PREDICTORS=True
INDICEPRIVACION=False
EXPERIMENT='OLDBASE'
MODELPATH=MODELSPATH+EXPERIMENT+'/'
ALGORITHM='logistic'
CONFIGNAME='logisticOLDBASE.py'
PREDPATH=os.path.join(OUTPATH,EXPERIMENT)
PREDFILES={yr: os.path.join(PREDPATH,'{1}{0}.csv'.format(yr,ALGORITHM)) for yr in [2016,2017,2018]}
COLUMNS=['urg']
TRACEBACK=True
EXCLUDE=None